on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    # Tipe mesin yang akan digunakan untuk menjalankan job
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      # Mengunduh repositori Anda agar dapat diakses oleh job
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup PHP
      # Mengkonfigurasi lingkungan PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath
          coverage: none

      # 3. Cache dependencies
      # Mempercepat proses build di masa mendatang dengan menyimpan cache package composer
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # 4. Install dependencies
      # Menginstal dependensi proyek menggunakan Composer
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # 5. Copy environment file
      # Membuat file .env dari file contoh dan men-generate app key
      - name: Create .env file
        run: |
          cp .env.example .env
          php artisan key:generate

      # 6. Run tests
      # Menjalankan tes PHPUnit Anda
      - name: Run PHPUnit tests
        run: php artisan test
